apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l2nz1g4rs-python
  janus-idp.io/tekton: l2nz1g4rs-python
  backstage.io/kubernetes-id: l2nz1g4rs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l2nz1g4rs-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
