apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: l2nz1g4rs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l2nz1g4rs-python 
  name: l2nz1g4rs-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: l2nz1g4rs-python
    weight: 100 
