apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l2nz1g4rs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l2nz1g4rs-python 
  name: l2nz1g4rs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l2nz1g4rs-python 
